### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by stanols** [roughcoder/grunt-folder-list#6]
Loading "folder_list.js" tasks...ERROR
>>TypeError: Cannot read property '1' of null

Warning: Task "folder_list" not found. Use --force to continue.

Aborted due to warnings.

I tried to build project with grunt.loadNpmTasks('grunt-folder-list'); but it's failed.
But when I replaced the lib with old version it solve the problem. 
Does anybody have the same?

**Comment by nasikshafeek** [comment]
@Stanols which version did you replace to? having the same problem here. :(

**Comment by ArmorDarks** [comment]
This issue seems to be caused by `to` dependency...

**Comment by stanols** [comment]
Closed due to no relevance

**Comment by ArmorDarks** [comment]
was it fixed?
